# Generated by Django 4.1.6 on 2023-02-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='medicine',
            field=models.ManyToManyField(blank=True, to='api.medicine'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='medicine_ointment',
            field=models.ManyToManyField(blank=True, to='api.medicineointment'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='medicine_tablet',
            field=models.ManyToManyField(blank=True, to='api.medicinetablet'),
        ),
    ]
