# Generated by Django 4.1.6 on 2023-02-02 08:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patienthistory_medicine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorViewStorage',
            fields=[
                ('doctor_view_storage_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
